mariadb:
  architecture: "standalone"
  auth:
    database: "golist"
    username: "golist"
    password: "golist"
  imageRegistry: public.ecr.aws
  global:
    imageRegistry: public.ecr.aws
  image:
    registry: public.ecr.aws