apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: nginx-2
  namespace: argocd
spec:
  source:
    chart: nginx
    repoURL: 'oci://registry-1.docker.io/bitnamicharts'
    targetRevision: 22.5.3
    helm:
      releaseName: nginx-2
      valuesObject:
        image:
          registry: public.ecr.aws
          tag: 1.28-trixie-otel

  destination:
    namespace: golist
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
