apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: nginx
  namespace: argocd
spec:
  source:
    path: apps/nginx
    repoURL: 'https://github.com/nhduc2001kt/gitops-test.git'
    targetRevision: main
    helm:
      releaseName: nginx
      valuesObject:          
        nginx:
          global:
            security:
              allowInsecureImages: true`
          image:
            registry: public.ecr.aws
            # tag: 1.28-trixie-otel
            debug: true

  destination:
    namespace: golist
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
